name: 'Mailer Bot'

on: push

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Page'
        run:  echo "$(curl https://static.nytimes.com/email-content/CNB_sample.html)" >> result.html
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Beijing' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.88.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Page Result (${{env.REPORT_DATE}})
          html_body: file://result.html
          to: literature2022@aliyun.com
          from: GitHub Actions
